// Centralized realistic mock data for OmniAgents.

export type AgentStatus = "idle" | "running" | "success" | "error" | "queued";

export interface Agent {
  id: string;
  name: string;
  role: string;
  status: AgentStatus;
  model: string;
  skills: string[];
  tools: string[];
  contextWindow: string;
  temperature: number;
  tokens: number;
  cost: number;
  latencyMs: number;
  lastTask: string;
  health: number;
  systemPrompt: string;
  memorySummary: string;
}

export const agents: Agent[] = [
  {
    id: "planner",
    name: "Planner Agent",
    role: "Decomposes user goals into executable plans",
    status: "running",
    model: "gpt-4o",
    skills: ["Goal decomposition", "Dependency graphs", "Routing"],
    tools: ["task_decompose", "router", "memory_search"],
    contextWindow: "128K",
    temperature: 0.2,
    tokens: 184320,
    cost: 4.21,
    latencyMs: 820,
    lastTask: "Plan: Create API documentation for payments service",
    health: 98,
    systemPrompt:
      "You are the Planner Agent. Decompose the user goal into ordered tasks with dependencies, assigning each step to the best specialized agent. Output strict JSON.",
    memorySummary:
      "Recently planned 14 workflows for documentation, refactoring and QA. Strong recall on payments service architecture.",
  },
  {
    id: "research",
    name: "Research Agent",
    role: "Gathers context from docs, code, and the web",
    status: "success",
    model: "claude-3.5-sonnet",
    skills: ["Doc search", "Web search", "Code grep"],
    tools: ["web_search", "rag_retrieve", "code_search"],
    contextWindow: "200K",
    temperature: 0.3,
    tokens: 92110,
    cost: 2.18,
    latencyMs: 1240,
    lastTask: "Retrieved OpenAPI schema for /payments",
    health: 96,
    systemPrompt:
      "You are the Research Agent. Retrieve precise, well-sourced context. Always cite source IDs.",
    memorySummary: "Indexed 1,284 chunks from the payments-service repo last 24h.",
  },
  {
    id: "code",
    name: "Code Agent",
    role: "Writes, refactors and inspects code",
    status: "running",
    model: "gpt-4o",
    skills: ["TypeScript", "Python", "Refactor", "AST analysis"],
    tools: ["repo_read", "repo_write", "linter", "ast_parse"],
    contextWindow: "128K",
    temperature: 0.1,
    tokens: 271430,
    cost: 6.74,
    latencyMs: 1820,
    lastTask: "Inspecting /api/payments/* route handlers",
    health: 94,
    systemPrompt:
      "You are the Code Agent. Produce minimal, correct, well-typed diffs. Never invent APIs.",
    memorySummary: "Strong recall on payments-service handlers, schemas and middlewares.",
  },
  {
    id: "sql",
    name: "SQL Agent",
    role: "Generates and validates SQL safely",
    status: "idle",
    model: "gpt-4o-mini",
    skills: ["SQL", "Schema reasoning", "Query optimization"],
    tools: ["db_introspect", "db_query_dry_run"],
    contextWindow: "128K",
    temperature: 0.0,
    tokens: 38420,
    cost: 0.41,
    latencyMs: 610,
    lastTask: "Generated read-only revenue rollup query",
    health: 99,
    systemPrompt: "You are the SQL Agent. Prefer read-only queries. Validate against schema.",
    memorySummary: "Knows analytics, billing and payments schemas.",
  },
  {
    id: "qa",
    name: "QA/Test Agent",
    role: "Runs checklists and validates outputs",
    status: "queued",
    model: "claude-3.5-sonnet",
    skills: ["Test design", "Coverage analysis", "Property checks"],
    tools: ["test_runner", "checklist", "schema_validate"],
    contextWindow: "200K",
    temperature: 0.2,
    tokens: 64210,
    cost: 1.42,
    latencyMs: 940,
    lastTask: "Awaiting docs draft for QA pass",
    health: 97,
    systemPrompt:
      "You are QA Agent. Run the checklist deterministically. Report PASS/FAIL with evidence.",
    memorySummary: "Recent QA runs on 9 documentation deliverables.",
  },
  {
    id: "reviewer",
    name: "Reviewer Agent",
    role: "Final pass for clarity, correctness, tone",
    status: "idle",
    model: "gpt-4o",
    skills: ["Editorial", "Style guide", "Risk review"],
    tools: ["style_guide", "diff_review"],
    contextWindow: "128K",
    temperature: 0.3,
    tokens: 42110,
    cost: 1.02,
    latencyMs: 720,
    lastTask: "Reviewed onboarding doc — approved",
    health: 99,
    systemPrompt: "You are the Reviewer Agent. Enforce the style guide and flag risk.",
    memorySummary: "Style guide v3.2 fully indexed.",
  },
  {
    id: "docs",
    name: "Documentation Agent",
    role: "Generates technical documentation",
    status: "running",
    model: "claude-3.5-sonnet",
    skills: ["Markdown", "API docs", "Tutorials"],
    tools: ["markdown_writer", "schema_to_md"],
    contextWindow: "200K",
    temperature: 0.4,
    tokens: 110480,
    cost: 2.94,
    latencyMs: 1320,
    lastTask: "Drafting /payments endpoint reference",
    health: 95,
    systemPrompt: "You are the Documentation Agent. Produce clear, accurate developer docs.",
    memorySummary: "Templates: REST reference, quickstart, migration guide.",
  },
  {
    id: "security",
    name: "Security Agent",
    role: "Scans for unsafe patterns and secrets",
    status: "success",
    model: "gpt-4o-mini",
    skills: ["Secret scanning", "Prompt injection", "Policy enforcement"],
    tools: ["secret_scan", "policy_eval"],
    contextWindow: "128K",
    temperature: 0.0,
    tokens: 18230,
    cost: 0.22,
    latencyMs: 410,
    lastTask: "No PII leaks detected in last 200 traces",
    health: 100,
    systemPrompt: "You are the Security Agent. Block unsafe outputs. Enforce policy.",
    memorySummary: "Active policies: PII-v4, prompt-injection-v2, secret-scan-v3.",
  },
  {
    id: "deploy",
    name: "Deployment Agent",
    role: "Publishes artifacts to staging/prod",
    status: "idle",
    model: "gpt-4o-mini",
    skills: ["CI/CD", "Rollback", "Canary"],
    tools: ["ci_trigger", "artifact_publish", "rollback"],
    contextWindow: "128K",
    temperature: 0.0,
    tokens: 12410,
    cost: 0.18,
    latencyMs: 520,
    lastTask: "Published docs build #421 to staging",
    health: 99,
    systemPrompt: "You are the Deployment Agent. Promote artifacts safely with confirmations.",
    memorySummary: "Recent deploys: docs-site (3), payments-svc (1).",
  },
  {
    id: "cost",
    name: "Cost Optimizer Agent",
    role: "Suggests cheaper model / prompt routes",
    status: "success",
    model: "gpt-4o-mini",
    skills: ["Routing", "Prompt compression", "Caching"],
    tools: ["model_router", "prompt_compress", "cache_lookup"],
    contextWindow: "128K",
    temperature: 0.2,
    tokens: 28910,
    cost: 0.34,
    latencyMs: 290,
    lastTask: "Saved $182 this week via routing to gpt-4o-mini",
    health: 100,
    systemPrompt: "You are the Cost Optimizer. Reroute or compress when safe.",
    memorySummary: "Tracks 30d cost-per-success across all workflows.",
  },
];

export const recentExecutions = [
  {
    id: "exec_8a21",
    workflow: "API Docs · payments",
    status: "success",
    duration: "42s",
    cost: 0.86,
    tokens: 42180,
    started: "2m ago",
  },
  {
    id: "exec_8a20",
    workflow: "Refactor · billing.ts",
    status: "running",
    duration: "18s",
    cost: 0.31,
    tokens: 18420,
    started: "just now",
  },
  {
    id: "exec_8a19",
    workflow: "QA · onboarding flow",
    status: "success",
    duration: "1m 12s",
    cost: 1.22,
    tokens: 61210,
    started: "6m ago",
  },
  {
    id: "exec_8a18",
    workflow: "SQL · revenue rollup",
    status: "success",
    duration: "9s",
    cost: 0.08,
    tokens: 4120,
    started: "12m ago",
  },
  {
    id: "exec_8a17",
    workflow: "Security · prompt audit",
    status: "error",
    duration: "3s",
    cost: 0.02,
    tokens: 940,
    started: "14m ago",
  },
  {
    id: "exec_8a16",
    workflow: "Docs · changelog v4.2",
    status: "success",
    duration: "38s",
    cost: 0.74,
    tokens: 38120,
    started: "22m ago",
  },
  {
    id: "exec_8a15",
    workflow: "Deploy · docs-site #421",
    status: "success",
    duration: "1m 04s",
    cost: 0.11,
    tokens: 5210,
    started: "28m ago",
  },
  {
    id: "exec_8a14",
    workflow: "Research · vendor compare",
    status: "success",
    duration: "54s",
    cost: 0.91,
    tokens: 47210,
    started: "41m ago",
  },
];

export const dashboardSeries = Array.from({ length: 24 }, (_, i) => ({
  hour: `${i}:00`,
  tokens: Math.round(40000 + Math.sin(i / 3) * 18000 + Math.random() * 9000),
  cost: +(2 + Math.sin(i / 4) * 1.2 + Math.random() * 0.6).toFixed(2),
  latency: Math.round(700 + Math.sin(i / 2) * 220 + Math.random() * 180),
  success: Math.round(92 + Math.sin(i / 5) * 4 + Math.random() * 2),
}));

export const modelBreakdown = [
  { name: "GPT-4o", value: 42, color: "var(--electric)" },
  { name: "Claude 3.5", value: 28, color: "var(--violet)" },
  { name: "Gemini 1.5", value: 18, color: "var(--cyan)" },
  { name: "Llama 3.1", value: 12, color: "var(--emerald)" },
];

export const planSteps = [
  {
    step: 1,
    title: "Inspect API routes",
    agent: "Code Agent",
    priority: "High",
    deps: "—",
    est: "~1.2s",
    cost: 0.04,
  },
  {
    step: 2,
    title: "Read OpenAPI schema",
    agent: "Research Agent",
    priority: "High",
    deps: "1",
    est: "~0.8s",
    cost: 0.02,
  },
  {
    step: 3,
    title: "Generate markdown docs",
    agent: "Documentation Agent",
    priority: "High",
    deps: "1,2",
    est: "~3.4s",
    cost: 0.18,
  },
  {
    step: 4,
    title: "Review for missing endpoints",
    agent: "Reviewer Agent",
    priority: "Medium",
    deps: "3",
    est: "~1.1s",
    cost: 0.06,
  },
  {
    step: 5,
    title: "Run QA checklist",
    agent: "QA Agent",
    priority: "Medium",
    deps: "3",
    est: "~1.6s",
    cost: 0.08,
  },
  {
    step: 6,
    title: "Publish final documentation",
    agent: "Deployment Agent",
    priority: "Critical",
    deps: "4,5",
    est: "~0.9s",
    cost: 0.03,
  },
];

export const workflowNodes = [
  { id: "user", label: "User Request", kind: "input", x: 40, y: 200 },
  { id: "planner", label: "Planner", kind: "agent", x: 220, y: 200 },
  { id: "research", label: "Research", kind: "agent", x: 400, y: 110 },
  { id: "router", label: "Decision Router", kind: "router", x: 400, y: 290 },
  { id: "code", label: "Code Agent", kind: "agent", x: 600, y: 110 },
  { id: "qa", label: "QA Agent", kind: "agent", x: 600, y: 290 },
  { id: "reviewer", label: "Reviewer", kind: "agent", x: 800, y: 200 },
  { id: "final", label: "Final Answer", kind: "output", x: 940, y: 200 },
];

export const workflowEdges: Array<{ from: string; to: string }> = [
  { from: "user", to: "planner" },
  { from: "planner", to: "research" },
  { from: "planner", to: "router" },
  { from: "research", to: "code" },
  { from: "router", to: "qa" },
  { from: "code", to: "reviewer" },
  { from: "qa", to: "reviewer" },
  { from: "reviewer", to: "final" },
];

export const debugSteps = [
  {
    id: "s1",
    label: "Planner · decompose",
    agent: "Planner Agent",
    tokens: 1240,
    latency: 820,
    cost: 0.04,
    status: "success",
  },
  {
    id: "s2",
    label: "Research · fetch schema",
    agent: "Research Agent",
    tokens: 3820,
    latency: 1240,
    cost: 0.09,
    status: "success",
  },
  {
    id: "s3",
    label: "Code · scan routes",
    agent: "Code Agent",
    tokens: 6210,
    latency: 1820,
    cost: 0.18,
    status: "success",
  },
  {
    id: "s4",
    label: "Docs · draft v1",
    agent: "Documentation Agent",
    tokens: 9810,
    latency: 2620,
    cost: 0.31,
    status: "retry",
  },
  {
    id: "s5",
    label: "Docs · draft v2",
    agent: "Documentation Agent",
    tokens: 10120,
    latency: 2410,
    cost: 0.32,
    status: "success",
  },
  {
    id: "s6",
    label: "QA · checklist",
    agent: "QA Agent",
    tokens: 4120,
    latency: 940,
    cost: 0.11,
    status: "success",
  },
  {
    id: "s7",
    label: "Reviewer · final pass",
    agent: "Reviewer Agent",
    tokens: 2210,
    latency: 720,
    cost: 0.07,
    status: "success",
  },
];

export const prompts = [
  {
    id: "p1",
    name: "Planner · Decomposer",
    category: "Planner",
    version: "v4.2",
    edited: "2h ago",
    score: 96,
    runs: 1284,
  },
  {
    id: "p2",
    name: "Code · Refactor Diff",
    category: "Agent",
    version: "v3.1",
    edited: "1d ago",
    score: 92,
    runs: 940,
  },
  {
    id: "p3",
    name: "Reviewer · Style Pass",
    category: "Reviewer",
    version: "v2.7",
    edited: "3d ago",
    score: 94,
    runs: 612,
  },
  {
    id: "p4",
    name: "Tool · SQL Safe Exec",
    category: "Tool",
    version: "v1.9",
    edited: "5d ago",
    score: 99,
    runs: 380,
  },
  {
    id: "p5",
    name: "Safety · PII Filter",
    category: "Safety",
    version: "v5.0",
    edited: "1w ago",
    score: 100,
    runs: 2140,
  },
  {
    id: "p6",
    name: "Docs · API Reference",
    category: "Agent",
    version: "v2.3",
    edited: "4h ago",
    score: 95,
    runs: 421,
  },
];

export const memoryCards = [
  {
    id: "m1",
    kind: "Session",
    title: "Current goal",
    body: "Create API documentation for payments service",
    fresh: 100,
  },
  {
    id: "m2",
    kind: "Long-term",
    title: "Payments architecture",
    body: "Microservice, Stripe + Adyen, idempotent webhooks, 3DS2 flow.",
    fresh: 92,
  },
  {
    id: "m3",
    kind: "Retrieved",
    title: "OpenAPI fragment",
    body: "POST /payments/intents — creates a PaymentIntent with idempotency_key.",
    fresh: 88,
  },
  {
    id: "m4",
    kind: "Vector",
    title: "Top-k chunk · 0.94",
    body: "...retries use exponential backoff up to 5 attempts with jitter...",
    fresh: 84,
  },
  {
    id: "m5",
    kind: "Long-term",
    title: "Style guide v3.2",
    body: "Prefer active voice, second person, fenced code with language hint.",
    fresh: 78,
  },
  {
    id: "m6",
    kind: "Session",
    title: "Last reviewer note",
    body: "Add error-code table; clarify 402 vs 409 semantics.",
    fresh: 96,
  },
];

export const tools = [
  {
    name: "Gmail",
    connected: true,
    perms: "read,send",
    latency: 320,
    success: 99.4,
    lastUsed: "3m ago",
    errors: 1,
  },
  {
    name: "Calendar",
    connected: true,
    perms: "read,write",
    latency: 210,
    success: 99.8,
    lastUsed: "9m ago",
    errors: 0,
  },
  {
    name: "Slack",
    connected: true,
    perms: "post,read",
    latency: 180,
    success: 99.6,
    lastUsed: "1m ago",
    errors: 2,
  },
  {
    name: "GitHub",
    connected: true,
    perms: "repo,issues",
    latency: 410,
    success: 98.9,
    lastUsed: "just now",
    errors: 4,
  },
  { name: "Jira", connected: false, perms: "—", latency: 0, success: 0, lastUsed: "—", errors: 0 },
  {
    name: "Notion",
    connected: true,
    perms: "read,write",
    latency: 360,
    success: 99.1,
    lastUsed: "12m ago",
    errors: 1,
  },
  {
    name: "SQL Database",
    connected: true,
    perms: "read-only",
    latency: 90,
    success: 99.9,
    lastUsed: "4m ago",
    errors: 0,
  },
  {
    name: "File System",
    connected: true,
    perms: "scoped",
    latency: 40,
    success: 100,
    lastUsed: "1m ago",
    errors: 0,
  },
  {
    name: "Browser",
    connected: true,
    perms: "headless",
    latency: 1240,
    success: 96.2,
    lastUsed: "8m ago",
    errors: 7,
  },
  {
    name: "Python Runner",
    connected: true,
    perms: "sandbox",
    latency: 820,
    success: 98.4,
    lastUsed: "6m ago",
    errors: 3,
  },
  {
    name: "Deployment Tool",
    connected: true,
    perms: "staging,prod",
    latency: 1820,
    success: 99.5,
    lastUsed: "21m ago",
    errors: 1,
  },
];

export const costByWorkflow = [
  { name: "API Docs", cost: 184.2 },
  { name: "Refactor", cost: 142.7 },
  { name: "QA Suite", cost: 121.9 },
  { name: "Research", cost: 98.4 },
  { name: "Deploy", cost: 41.2 },
  { name: "SQL", cost: 22.1 },
];

export const costByAgent = agents.map((a) => ({
  name: a.name.replace(" Agent", ""),
  cost: +(a.cost * 12).toFixed(2),
}));

export const monthlyCost = Array.from({ length: 30 }, (_, i) => ({
  day: `${i + 1}`,
  cost: +(28 + Math.sin(i / 3) * 8 + Math.random() * 6).toFixed(2),
}));

export const alerts = [
  { kind: "High latency", detail: "Browser tool p95 > 2.4s", severity: "warn" },
  { kind: "Cost spike", detail: "Refactor workflow +38% vs 7d avg", severity: "warn" },
  { kind: "Tool failure", detail: "GitHub 5xx rate 0.8%", severity: "error" },
  { kind: "Memory slow", detail: "Vector recall p95 > 380ms", severity: "warn" },
  { kind: "Retry loop", detail: "Docs draft retried 3x on exec_8a04", severity: "error" },
];
