import { agents as mockAgents } from "@/lib/mock-data";
import {
  FINAL_OUTPUT_FILENAME,
  FINAL_OUTPUT_MARKDOWN,
  FINAL_OUTPUT_TITLE,
} from "@/lib/final-output";
import type { Agent, DemoNodeId, DemoScenario, ExecutionRecord, WorkflowStep } from "./types";

export const DEMO_RUN_ID = "exec_8a22";

export const DEMO_WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: "user",
    label: "User Request",
    agent: "—",
    kind: "input",
    order: 1,
    description: "A stakeholder asks for production-grade payments API documentation.",
    model: "human",
    promptSummary: "Create investor-demo quality API documentation for the payments service.",
    inputSummary:
      "Stakeholder request with target audience, service name, and expected final artifact.",
    memoryContext: ["current_session_goal", "demo_positioning_client_investor_ready"],
    outputSummary: "Goal accepted and normalized for agent planning.",
    latencyMs: 120,
    tokens: 220,
    cost: 0,
  },
  {
    id: "planner",
    label: "Planner",
    agent: "Planner Agent",
    kind: "agent",
    order: 2,
    description: "Breaks the goal into dependent tasks and assigns specialist agents.",
    model: "gpt-4o",
    promptSummary: "Decompose the request into ordered tasks with agent ownership and checks.",
    inputSummary: "Normalized goal, payments service scope, and demo constraints.",
    memoryContext: ["agent_roster", "payments_arch_v3", "style_guide_v3.2"],
    outputSummary: "Six-agent execution plan with retrieval, code scan, docs, QA, and review.",
    latencyMs: 820,
    tokens: 1240,
    cost: 0.04,
  },
  {
    id: "research",
    label: "Research",
    agent: "Research Agent",
    kind: "agent",
    order: 3,
    description: "Retrieves OpenAPI context, style guides, and relevant source references.",
    model: "claude-3.5-sonnet",
    promptSummary: "Retrieve authoritative context for payments API documentation.",
    inputSummary: "Planning task, schema id openapi://payments@v4.2, and style guide reference.",
    memoryContext: ["openapi_payments_v4.2", "style_guide_v3.2", "payments_release_notes"],
    outputSummary: "14 high-similarity context chunks prepared for downstream agents.",
    latencyMs: 1240,
    tokens: 3820,
    cost: 0.09,
  },
  {
    id: "code",
    label: "Code",
    agent: "Code Agent",
    kind: "agent",
    order: 4,
    description: "Scans route handlers and extracts endpoint/schema details.",
    model: "gpt-4o",
    promptSummary: "Inspect payments route handlers and extract endpoint/schema evidence.",
    inputSummary: "Retrieved API context plus /api/payments/* source targets.",
    memoryContext: ["payments_routes_index", "zod_schema_registry", "auth_policy_notes"],
    outputSummary: "12 endpoints mapped to request, response, auth, and error semantics.",
    latencyMs: 1820,
    tokens: 6210,
    cost: 0.18,
  },
  {
    id: "docs",
    label: "Documentation",
    agent: "Documentation Agent",
    kind: "agent",
    order: 5,
    description: "Drafts the markdown API reference and handles schema conversion retries.",
    model: "claude-3.5-sonnet",
    promptSummary: "Draft a complete markdown API reference from schema and code evidence.",
    inputSummary: "Endpoint map, OpenAPI chunks, style rules, and artifact requirements.",
    memoryContext: ["draft:payments_docs:v1", "style_guide_v3.2", "openapi_payments_v4.2"],
    outputSummary: "18.4KB markdown draft produced after one recovered schema conversion retry.",
    latencyMs: 5030,
    tokens: 19930,
    cost: 0.63,
  },
  {
    id: "qa",
    label: "QA",
    agent: "QA/Test Agent",
    kind: "agent",
    order: 6,
    description: "Runs a deterministic quality checklist against the generated artifact.",
    model: "claude-3.5-sonnet",
    promptSummary: "Validate the generated API reference against QA and governance criteria.",
    inputSummary: "Markdown draft, endpoint map, style guide, and expected checklist.",
    memoryContext: ["qa_checklist_api_docs_v2", "draft:payments_docs:v2", "risk_policy_low"],
    outputSummary: "14/14 checklist items passed with an added error-code table.",
    latencyMs: 940,
    tokens: 4120,
    cost: 0.11,
  },
  {
    id: "reviewer",
    label: "Reviewer",
    agent: "Reviewer Agent",
    kind: "agent",
    order: 7,
    description: "Enforces style, checks risk, and approves the final artifact.",
    model: "gpt-4o",
    promptSummary: "Review the final documentation for clarity, risk, and business readiness.",
    inputSummary: "QA-approved markdown, issue log, and reviewer acceptance criteria.",
    memoryContext: ["style_guide_v3.2", "governance_policy_docs", "qa_pass_report"],
    outputSummary: "Approved final artifact with low risk and three minor style edits.",
    latencyMs: 720,
    tokens: 2210,
    cost: 0.07,
  },
  {
    id: "final",
    label: "Final Output",
    agent: "—",
    kind: "output",
    order: 8,
    description: "Publishes the approved client-ready markdown artifact.",
    model: "artifact publisher",
    promptSummary: "Publish the approved markdown artifact for demo presentation.",
    inputSummary: "Reviewer-approved markdown and artifact metadata.",
    memoryContext: ["artifact_registry", "approval:reviewer:low_risk"],
    outputSummary: "payments-api-v4.2.md published as the final approved artifact.",
    latencyMs: 240,
    tokens: 120,
    cost: 0,
  },
];

export const DEMO_NODES = DEMO_WORKFLOW_STEPS.map(({ id, label, agent }) => ({
  id,
  label,
  agent,
})) as Array<{ id: DemoNodeId; label: string; agent: string }>;

export const DEMO_EXECUTION: ExecutionRecord = {
  id: DEMO_RUN_ID,
  workflow: "Demo Run · all agents",
  status: "success",
  duration: "58s",
  tokens: 68420,
  cost: 1.24,
  started: "just now",
  isDemo: true,
};

export const DEMO_STEP_MESSAGES: DemoScenario["stepMessages"] = {
  user: [
    {
      msg: "Goal received: Create API documentation for payments service",
      tone: "info",
      type: "status",
    },
  ],
  planner: [
    { msg: "Decomposing goal into 6 subtasks", tone: "info", type: "prompt", latencyMs: 410 },
    {
      msg: "Dependency graph built · routed to 5 agents",
      tone: "success",
      type: "status",
      latencyMs: 820,
      cost: 0.04,
    },
  ],
  research: [
    {
      msg: "RAG retrieve openapi://payments@v4.2 · 0.94 similarity",
      tone: "info",
      type: "tool_call",
      latencyMs: 640,
      toolCallId: "tool_rag_retrieve",
    },
    {
      msg: "Retrieved 14 context chunks (1,284 tokens)",
      tone: "success",
      type: "tool_result",
      latencyMs: 1240,
      cost: 0.09,
      toolCallId: "tool_rag_retrieve",
    },
  ],
  code: [
    {
      msg: "Scanning /api/payments/* route handlers",
      tone: "info",
      type: "tool_call",
      latencyMs: 980,
      toolCallId: "tool_code_search",
    },
    {
      msg: "Found 12 endpoints · extracted Zod schemas",
      tone: "success",
      type: "tool_result",
      latencyMs: 1820,
      cost: 0.18,
      toolCallId: "tool_code_search",
    },
  ],
  docs: [
    { msg: "Drafting markdown reference v1", tone: "info", type: "prompt", latencyMs: 910 },
    {
      msg: "ToolTimeoutError schema_to_md > 2500ms · retry in 600ms",
      tone: "warn",
      type: "retry",
      latencyMs: 2500,
      toolCallId: "tool_schema_to_md_retry",
    },
    {
      msg: "Draft v2 complete · 18.4KB markdown",
      tone: "success",
      type: "tool_result",
      latencyMs: 5030,
      cost: 0.63,
      toolCallId: "tool_schema_to_md_retry",
    },
  ],
  qa: [
    {
      msg: "Running checklist · 14 items",
      tone: "info",
      type: "tool_call",
      latencyMs: 520,
      toolCallId: "tool_checklist",
    },
    {
      msg: "QA passed 14/14 · added error-code table",
      tone: "success",
      type: "review",
      latencyMs: 940,
      cost: 0.11,
      toolCallId: "tool_checklist",
    },
  ],
  reviewer: [
    { msg: "Style guide v3.2 enforced · 3 micro edits", tone: "info", type: "review" },
    { msg: "Approved · risk = low", tone: "success", type: "review", latencyMs: 720, cost: 0.07 },
  ],
  final: [
    {
      msg: "Artifact published · payments-api-v4.2.md",
      tone: "success",
      type: "artifact",
      latencyMs: 240,
    },
  ],
};

export const DEMO_SCENARIO: DemoScenario = {
  id: "payments-api-docs",
  name: "Payments API documentation",
  goal: "Create API documentation for payments service",
  description:
    "A deterministic investor demo showing planning, retrieval, code inspection, documentation, QA, review, and final artifact publication.",
  agents: mockAgents as Agent[],
  steps: DEMO_WORKFLOW_STEPS,
  toolCalls: [
    {
      id: "tool_rag_retrieve",
      runId: DEMO_RUN_ID,
      stepId: "research",
      tool: "rag_retrieve",
      status: "success",
      latencyMs: 1240,
      inputSummary: "Retrieve OpenAPI schema, style guide, and payments service notes.",
      outputSummary: "Returned 14 high-similarity context chunks.",
    },
    {
      id: "tool_code_search",
      runId: DEMO_RUN_ID,
      stepId: "code",
      tool: "code_search",
      status: "success",
      latencyMs: 1820,
      inputSummary: "Scan /api/payments/* route handlers and Zod schemas.",
      outputSummary: "Found 12 endpoints and extracted request/response models.",
    },
    {
      id: "tool_schema_to_md_retry",
      runId: DEMO_RUN_ID,
      stepId: "docs",
      tool: "schema_to_md",
      status: "retry",
      latencyMs: 2500,
      inputSummary: "Serialize openapi://payments@v4.2 to GitHub markdown.",
      outputSummary: "Timed out once, then recovered with exponential backoff.",
    },
    {
      id: "tool_checklist",
      runId: DEMO_RUN_ID,
      stepId: "qa",
      tool: "checklist",
      status: "success",
      latencyMs: 940,
      inputSummary: "Validate generated markdown against 14 QA criteria.",
      outputSummary: "Passed 14/14 checks.",
    },
  ],
  costSummary: {
    runId: DEMO_RUN_ID,
    totalCost: DEMO_EXECUTION.cost,
    totalTokens: DEMO_EXECUTION.tokens,
    estimatedManualHours: "4-6h",
    modelSavingsPercent: 32,
  },
  finalArtifact: {
    runId: DEMO_RUN_ID,
    title: FINAL_OUTPUT_TITLE,
    filename: FINAL_OUTPUT_FILENAME,
    sizeLabel: "18.4 KB",
    status: "approved",
    approvedBy: "Reviewer",
    markdown: FINAL_OUTPUT_MARKDOWN,
  },
  executionRecord: DEMO_EXECUTION,
  stepMessages: DEMO_STEP_MESSAGES,
};
