/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as DebuggerRouteImport } from './routes/debugger'
import { Route as CostRouteImport } from './routes/cost'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperApiRouteImport } from './routes/developer.api'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggerRoute = DebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperApiRoute = DeveloperApiRouteImport.update({
  id: '/developer/api',
  path: '/developer/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cost': typeof CostRoute
  '/debugger': typeof DebuggerRoute
  '/evals': typeof EvalsRoute
  '/memory': typeof MemoryRoute
  '/monitoring': typeof MonitoringRoute
  '/planner': typeof PlannerRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/workflow': typeof WorkflowRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/developer/api': typeof DeveloperApiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cost': typeof CostRoute
  '/debugger': typeof DebuggerRoute
  '/evals': typeof EvalsRoute
  '/memory': typeof MemoryRoute
  '/monitoring': typeof MonitoringRoute
  '/planner': typeof PlannerRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/workflow': typeof WorkflowRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/developer/api': typeof DeveloperApiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cost': typeof CostRoute
  '/debugger': typeof DebuggerRoute
  '/evals': typeof EvalsRoute
  '/memory': typeof MemoryRoute
  '/monitoring': typeof MonitoringRoute
  '/planner': typeof PlannerRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/workflow': typeof WorkflowRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/developer/api': typeof DeveloperApiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/cost'
    | '/debugger'
    | '/evals'
    | '/memory'
    | '/monitoring'
    | '/planner'
    | '/prompts'
    | '/settings'
    | '/tools'
    | '/workflow'
    | '/admin/analytics'
    | '/developer/api'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/cost'
    | '/debugger'
    | '/evals'
    | '/memory'
    | '/monitoring'
    | '/planner'
    | '/prompts'
    | '/settings'
    | '/tools'
    | '/workflow'
    | '/admin/analytics'
    | '/developer/api'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/cost'
    | '/debugger'
    | '/evals'
    | '/memory'
    | '/monitoring'
    | '/planner'
    | '/prompts'
    | '/settings'
    | '/tools'
    | '/workflow'
    | '/admin/analytics'
    | '/developer/api'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  CostRoute: typeof CostRoute
  DebuggerRoute: typeof DebuggerRoute
  EvalsRoute: typeof EvalsRoute
  MemoryRoute: typeof MemoryRoute
  MonitoringRoute: typeof MonitoringRoute
  PlannerRoute: typeof PlannerRoute
  PromptsRoute: typeof PromptsRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  WorkflowRoute: typeof WorkflowRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  DeveloperApiRoute: typeof DeveloperApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugger': {
      id: '/debugger'
      path: '/debugger'
      fullPath: '/debugger'
      preLoaderRoute: typeof DebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/api': {
      id: '/developer/api'
      path: '/developer/api'
      fullPath: '/developer/api'
      preLoaderRoute: typeof DeveloperApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  CostRoute: CostRoute,
  DebuggerRoute: DebuggerRoute,
  EvalsRoute: EvalsRoute,
  MemoryRoute: MemoryRoute,
  MonitoringRoute: MonitoringRoute,
  PlannerRoute: PlannerRoute,
  PromptsRoute: PromptsRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  WorkflowRoute: WorkflowRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  DeveloperApiRoute: DeveloperApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
